# syntax=docker/dockerfile:1.14.0-labs
FROM node:22.14.0-slim

ENV APP_HOME=/home/app

RUN mkdir -p $APP_HOME/node_modules && chown -R node:node $APP_HOME

WORKDIR $APP_HOME

COPY package.json ./
COPY --parents web/*/package.json .

RUN npm install

COPY web ./web
COPY pm2.json ./

RUN cd web/remix && npm run build

EXPOSE 3001
CMD [ "npx", "pm2", "start", "--no-daemon", "./pm2.json" ]
