services:
  db:
    image: postgres:17-alpine
    container_name: remix-watt-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: watt-remix-demo
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4096M
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "3042:3042"
      - "4042:4042"
    depends_on:
      - db

  app2:
    build: 
      context: .
      dockerfile: Dockerfile-pm2
    image: watt-remix-demo-pm2
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4096M
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
